#!/bin/bash
#
# Usage: ~/bin/build-kernel $device $log
#
device="davinci"
log="log.txt"

source ~/binaries/helper
export USE_CCACHE=1
/usr/bin/ccache -M 20G
DATE_START=$(date +"%s")

MONTH=$(date -d "$D" '+%m')
YEAR=$(date -d "$D" '+%Y')

OS="11.0.0"
SPL="${YEAR}-${MONTH}"

rm -rf ~/out/arch/arm64/boot/dts/xiaomi/

command make O=~/out \
  ARCH=arm64 \
  vendor/lineage_${device}_defconfig

export PATH=~/binaries/toolchain/clang/bin:~/binaries/toolchain/gcc-64/bin:~/binaries/toolchain/gcc-32/bin/:~/binaries/toolchain/dtc:${PATH}

command make -j$(nproc) O=~/out \
  ARCH=arm64 \
  CC=clang \
  CLANG_TRIPLE=aarch64-linux-gnu- \
  CROSS_COMPILE=aarch64-linux-android- \
  CROSS_COMPILE_ARM32=arm-linux-androideabi- \
  DTC_EXT=dtc \
  2>&1 | tee ~/${log}

find ~/out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + > /tmp/${device}.dtb
~/bin/mkbootimg/mkbootimg \
    --kernel ~/out/arch/arm64/boot/Image.gz-dtb \
    --cmdline 'androidboot.hardware=qcom androidboot.console=ttyMSM0 service_locator.enable=1 swiotlb=1 earlycon=msm_geni_serial,0x880000 loop.max_part=7 cgroup.memory=nokmem,nosocket androidboot.vbmeta.avb_version=1.0' \
    --base           0x00000000 \
    --pagesize       4096 \
    --dtb            /tmp/${device}.dtb \
    --os_version     $OS \
    --os_patch_level $SPL \
    -o ~/out/boot.img

file  ~/out/boot.img
 
~/bin/libufdt/utils/src/mkdtboimg.py create ~/out/dtbo-pre.img \
  --page_size=4096 \
  `find ~/out/arch/arm64/boot/dts/xiaomi \
  -type f -name '*.dtbo' | sort`

file ~/out/dtbo-pre.img

header "Build Completed in:"

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
success "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
