#!/bin/bash
source ~/bin/helper
export USE_CCACHE=1
/usr/bin/ccache -M 20G
DATE_START=$(date +"%s")

export OS="10.0.0"
export SPL="2020-07"

rm -rf ~/out/arch/arm64/boot/dts/xiaomi/

command make O=~/out \
  ARCH=arm64 \
  vendor/lineage_davinci_defconfig

export PATH=~/bin/toolchain/clang/clang-r353983c1/bin:~/bin/toolchain/gcc-64/bin:~/bin/toolchain/gcc-32/bin/:${PATH}

command make -j4 O=~/out \
  ARCH=arm64 \
  CC=clang \
  CLANG_TRIPLE=aarch64-linux-gnu- \
  CROSS_COMPILE=aarch64-linux-android- \
  CROSS_COMPILE_ARM32=arm-linux-androideabi-

find ~/out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + > /tmp/davinci.dtb
~/bin/mkbootimg/mkbootimg \
    --kernel ~/out/arch/arm64/boot/Image.gz-dtb \
    --cmdline 'androidboot.hardware=qcom androidboot.console=ttyMSM0 service_locator.enable=1 swiotlb=1 earlycon=msm_geni_serial,0x880000 loop.max_part=7 cgroup.memory=nokmem,nosocket androidboot.vbmeta.avb_version=1.0' \
    --base           0x00000000 \
    --pagesize       4096 \
    --kernel_offset  0x00008000 \
    --second_offset  0x00f00000 \
    --tags_offset    0x00000100 \
    --dtb            /tmp/davinci.dtb \
    --os_version     $OS \
    --os_patch_level $SPL \
    --header_version 1 \
    -o ~/out/boot.img

file  ~/out/boot.img

~/bin/mkdtimg create ~/out/dtbo-pre.img \
  --page_size=4096 \
  `find ~/out/arch/arm64/boot/dts/xiaomi \
  -type f -name '*.dtbo' | sort`

file ~/out/dtbo-pre.img

header "Build Completed in:"

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
success "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."

~/bin/flash
