#!/bin/bash

source ~/bin/helper

function setup() {
source build/envsetup.sh
mka installclean
}

function buildsigned() {
mka target-files-package otatools -j$( nproc --all )

./build/tools/releasetools/sign_target_files_apks -o -d ~/.android-certs \
    $OUT/obj/PACKAGING/target_files_intermediates/*-target_files-*.zip \
    signed-target_files.zip

./build/tools/releasetools/ota_from_target_files -k ~/.android-certs/releasekey \
    --block --backup=true \
    signed-target_files.zip \
    signed-ota_update.zip

mv signed-ota_update.zip /home/builder/dl/losq/davinci/lineage-17.1-$(date +%F | sed s@-@@g)-UNOFFICIAL-davinci.zip
}

function buildbacon() {
mka bacon -j
}

function buildtype() {
info "Do you want a signed build?"
read -p "options: (yes/no)" option
case $option in
  y | Y | yes | Yes)
    buildsigned
    ;;
  n | N | no | No)
    buildbacon
    ;;
esac
}

function sync() {
repo sync -q -j$( nproc --all ) --force-sync --force-remove-dirty -c --no-clone-bundle --no-tags --optimized-fetch --prune 
}

function fetch() {
git -C device/xiaomi/davinci/ fetch -q https://github.com/sm6150-dev/android_device_xiaomi_davinci && git -C device/xiaomi/davinci/ checkout FETCH_HEAD
git -C device/xiaomi/sm6150-common/ fetch -q https://github.com/sm6150-dev/android_device_xiaomi_sm6150-common && git -C device/xiaomi/sm6150-common/ checkout FETCH_HEAD
git -C kernel/xiaomi/sm6150/ fetch -q https://github.com/sm6150-dev/android_kernel_xiaomi_sm6150 && git -C kernel/xiaomi/sm6150/ checkout FETCH_HEAD
info "Fetching latest sm6150-dev source..."
clear
}

function pick() {
set -e
changes=(
272303 # DozeSensors: only use proximity sensor if supported
266130 # FODCircleView: Add Support for custom FP pressed icon
280082 # FingerprintService: hide InDisplayFingerprintView on Error
276156 # sdm: mark FOD pressed layer by setting a bit on ZPOS
279890 # Allow to drop existing fd cache of cgroup path
281412 # SystemUI: Don't re add brightness slider if its already present
)
repopick ${changes[@]}&
info "Picking separate commits from gerrit..."
clear
}

function pull() {
repopick -p 278063 # hal: Add tfa98xx feedback extension
repopick -p 277176 # VolumeDialog: Implement expand/collapse animation
repopick -p 279893 # [DNM] Enable USAP by default
repopick -p 275821 # interfaces: Fix blueprint generation
repopick -p 272451 # org.ifaa.android.manager: Add ifaa apis to unrestricted greylist
repopick -p 277273 # MediaProvider: Check hidden directories recursively
repopick -p 278021 # FODCircleView: let's smoothly fade-out the view, before going to View.GONE
info "Pulling commits from gerrit..."
clear
}

function topic() {
repopick -t ten-firewall
info "Picking topics from gerrit..."
clear
}

function build() {
clear

DATE_START=$(date +"%s")
buildtype

header "Build Completed in:"

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
success "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
success
}

setup
sync
fetch
pick
pull
topic
build
