#!/bin/bash

source ~/bin/helper
source build/envsetup.sh

function sync() {
repo sync -q -j$( nproc --all ) --force-sync --force-remove-dirty -c --no-clone-bundle --no-tags --optimized-fetch --prune 
}

function fetch() {
git -C device/xiaomi/davinci/ fetch -q https://github.com/sm6150-dev/android_device_xiaomi_davinci && git -C device/xiaomi/davinci/ checkout FETCH_HEAD
git -C device/xiaomi/sm6150-common/ fetch -q https://github.com/sm6150-dev/android_device_xiaomi_sm6150-common refs/for/lineage-17.1 && git -C device/xiaomi/sm6150-common/ checkout FETCH_HEAD
info "Fetching latest sm6150-dev source..."
clear
}

function pick() {
set -e
changes=(
#272303 # DozeSensors: only use proximity sensor if supported
266130 # FODCircleView: Add Support for custom FP pressed icon
#280082 # FingerprintService: hide InDisplayFingerprintView on Error
#281412 # SystemUI: Don't re add brightness slider if its already present
)
repopick ${changes[@]}&
info "Picking separate commits from gerrit..."
clear
}

function pull() {
repopick -p 278063 -P hardware/qcom-caf/sm8150/audio # hal: Add tfa98xx feedback extension
#repopick -p 275821 # interfaces: Fix blueprint generation
#repopick -p 272451 # org.ifaa.android.manager: Add ifaa apis to unrestricted greylist
repopick -p 277273 # MediaProvider: Check hidden directories recursively
repopick -p 282518 # Launcher3: improve protected app names style
info "Pulling commits from gerrit..."
clear
}

function topic() {
#repopick -t ten-firewall
#repopick -t xiaomi-power-hal
#repopick -t ten-dtbo
repopick -t screen-off-fod
info "Picking topics from gerrit..."
clear
}

function build() {
clear

DATE_START=$(date +"%s")
buildtype

header "Build Completed in:"

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
success "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
success
}

sync
#fetch
pick
pull
topic
